//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon close_window_24 {
            get {
                object obj = ResourceManager.GetObject("close-window-24", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;name&quot;: &quot;file-error-test&quot;,
        ///  &quot;capabilities&quot;: [ &quot;DarkMode&quot;, &quot;File&quot;, &quot;Error&quot; ],
        ///  &quot;version&quot;: 2,
        ///  &quot;colors&quot;: {
        ///    &quot;backColor&quot;: &quot;#082a56&quot;,
        ///    &quot;foreColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonForeColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonHoverColor&quot;: &quot;#082a56&quot;,
        ///    &quot;comboBoxItemBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;comboBoxItemHoverColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlForeColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlHighlightColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlHighlightLightColor&quot;: &quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CONFIG_THEMING_THEME_FILE_TEST_2_theme {
            get {
                return ResourceManager.GetString("CONFIG_THEMING_THEME_FILE_TEST_2.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;name&quot;: &quot;file-ok-test&quot;,
        ///  &quot;capabilities&quot;: [ &quot;DarkMode&quot;, &quot;File&quot;, &quot;OK&quot; ],
        ///  &quot;version&quot;: 2,
        ///  &quot;colors&quot;: {
        ///    &quot;backColor&quot;: &quot;#082a56&quot;,
        ///    &quot;foreColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonForeColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonHoverColor&quot;: &quot;#082a56&quot;,
        ///    &quot;comboBoxItemBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;comboBoxItemHoverColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlForeColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlHighlightColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlHighlightLightColor&quot;: &quot;#082a5 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CONFIG_THEMING_THEME_FILE_TEST_theme {
            get {
                return ResourceManager.GetString("CONFIG_THEMING_THEME_FILE_TEST.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///  &quot;name&quot;: &quot;resource-file-test&quot;,
        ///  &quot;capabilities&quot;: [ &quot;DarkMode&quot;, &quot;Resource-File&quot; ],
        ///  &quot;version&quot;: 2,
        ///  &quot;colors&quot;: {
        ///    &quot;backColor&quot;: &quot;#082a56&quot;,
        ///    &quot;foreColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonForeColor&quot;: &quot;#082a56&quot;,
        ///    &quot;buttonHoverColor&quot;: &quot;#082a56&quot;,
        ///    &quot;comboBoxItemBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;comboBoxItemHoverColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlBackColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlForeColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlHighlightColor&quot;: &quot;#082a56&quot;,
        ///    &quot;controlHighlightLightColor&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string CONFIG_THEMING_THEME_RESOURCE_TEST_theme {
            get {
                return ResourceManager.GetString("CONFIG_THEMING_THEME_RESOURCE_TEST.theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;name&quot;: &quot;theme-name&quot;,
        ///	&quot;version&quot;: 2,
        ///	&quot;colors&quot;: {
        ///		&quot;backColor&quot;: &quot;#082a56&quot;,
        ///		&quot;foreColor&quot;: &quot;#082a56&quot;,
        ///		&quot;buttonBackColor&quot;: &quot;#082a56&quot;,
        ///		&quot;buttonForeColor&quot;: &quot;#082a56&quot;,
        ///		&quot;buttonHoverColor&quot;: &quot;#082a56&quot;,
        ///		&quot;comboBoxItemBackColor&quot;: &quot;#082a56&quot;,
        ///		&quot;comboBoxItemHoverColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlBackColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlForeColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlHighlightColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlHighlightLightColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlHighlightDarkColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlBorderColor&quot;: &quot;#08 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MISSING_CAPS {
            get {
                return ResourceManager.GetString("MISSING_CAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;name&quot;: &quot;theme-name&quot;,
        ///	&quot;capabilities&quot;: [&quot;DarkMode&quot;, &quot;HighContrast&quot;],
        ///	&quot;version&quot;: 2,
        ///	&quot;colors&quot;: {
        ///	}
        ///} ähnelt.
        /// </summary>
        internal static string MISSING_COLORS {
            get {
                return ResourceManager.GetString("MISSING_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;capabilities&quot;: [&quot;DarkMode&quot;, &quot;HighContrast&quot;],
        ///	&quot;version&quot;: 2,
        ///	&quot;colors&quot;: {
        ///		&quot;backColor&quot;: &quot;#082a56&quot;,
        ///		&quot;foreColor&quot;: &quot;#082a56&quot;,
        ///		&quot;buttonBackColor&quot;: &quot;#082a56&quot;,
        ///		&quot;buttonForeColor&quot;: &quot;#082a56&quot;,
        ///		&quot;buttonHoverColor&quot;: &quot;#082a56&quot;,
        ///		&quot;comboBoxItemBackColor&quot;: &quot;#082a56&quot;,
        ///		&quot;comboBoxItemHoverColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlBackColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlForeColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlHighlightColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlHighlightLightColor&quot;: &quot;#082a56&quot;,
        ///		&quot;controlHighlightDarkColor&quot;: &quot;#082a56&quot;,
        ///		&quot;c [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MISSING_NAME {
            get {
                return ResourceManager.GetString("MISSING_NAME", resourceCulture);
            }
        }
    }
}
