# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pullrequest

on:
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      checks: write
      pull-requests: write
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore WinFormsThemes/WinFormsThemes.sln
    - name: Build
      run: dotnet build WinFormsThemes/WinFormsThemes.sln --no-restore
    - name: run unittests
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: WinFormsThemes/TestProject
        report_name: Unittests
        report_title: Unittests
        set_check_status_from_test_outcome: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test Coverage
      run: dotnet test WinFormsThemes/TestProject --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Workaround for backslashes in path https://github.com/5monkeys/cobertura-action/issues/86
      run: (Get-Content -path ./coverage/**/coverage.cobertura.xml -Raw) -replace '\\','/' | out-file -FilePath ./coverage/**/coverage.cobertura.xml
    - uses: 5monkeys/cobertura-action@master
      with:
        path: ./coverage/**/coverage.cobertura.xml
        skip_covered: false
        show_missing: true
        link_missing_lines: true
        link_missing_lines_source_dir: WinFormsThemes/WinFormsThemes
        minimum_coverage: 80
    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-output
        path: |
          LICENSE
          WinFormsThemes/WinFormsThemes/bin/Debug/net6.0-windows/WinFormsThemes.dll
          WinFormsThemes/WinFormsThemes/bin/Debug/*.nupkg
          WinFormsThemes/WinFormsThemes/bin/Debug/*.snupkg
        if-no-files-found: error

      
